Repository Adyen/adyen-salesforce-commerce-cloud, pull requests merged in 2023-04, with the labels that each got.

#899 Adyen Giving 2.0
  metadata/site_import/meta/system-objecttype-extensions.xml
  metadata/site_import/services.xml
  src/cartridges/int_adyen_SFRA/cartridge/controllers/middlewares/order/confirm.js
  src/cartridges/int_adyen_overlay/cartridge/adyenConstants/constants.js
  src/cartridges/int_adyen_overlay/cartridge/scripts/adyenGiving.js
  src/cartridges/int_adyen_overlay/cartridge/scripts/handleCustomObject.js
  src/cartridges/int_adyen_overlay/cartridge/scripts/handleNotify.js
  src/cartridges/int_adyen_overlay/cartridge/scripts/util/adyenHelper.js
Labels: new

#900 Introduce separate constants for API version and Web Components between SG and SFRA
  jest/sfccCartridgeMocks.js
  metadata/site_import/services.xml
  src/cartridges/int_adyen_SFRA/cartridge/scripts/adyenService.js
  src/cartridges/int_adyen_controllers/cartridge/scripts/adyenService.js
  src/cartridges/int_adyen_overlay/cartridge/adyenConstants/constants.js
  src/cartridges/int_adyen_overlay/cartridge/scripts/adyenCheckout.js
  src/cartridges/int_adyen_overlay/cartridge/scripts/adyenGetPaymentMethods.js
  src/cartridges/int_adyen_overlay/cartridge/scripts/adyenGiving.js
  src/cartridges/int_adyen_overlay/cartridge/scripts/adyenSessions.js
  src/cartridges/int_adyen_overlay/cartridge/scripts/util/adyenHelper.js
Labels: refactor

#904 Outdated references to a non-existing file are present
  src/cartridges/int_adyen_SFRA/cartridge/templates/default/checkout/billing/adyenPosForm.isml
  src/cartridges/int_adyen_SFRA/cartridge/templates/default/checkout/billing/paymentOptions/adyenComponentSummary.isml
  src/cartridges/int_adyen_controllers/cartridge/templates/default/account/payment/adyenpaymentinstrumentdetails.isml
  src/cartridges/int_adyen_controllers/cartridge/templates/default/adyenOrderDetails.isml
  src/cartridges/int_adyen_controllers/cartridge/templates/default/checkout/billing/adyenGivingComponent.isml
Labels: fix

#903 Show Correct Tax Amount In Klarna Playground
  src/cartridges/int_adyen_overlay/cartridge/scripts/adyenGetOpenInvoiceData.js
Labels: fix

#906 Re-render components to reflect updated amount
  src/cartridges/int_adyen_SFRA/cartridge/client/default/js/adyen_checkout/checkoutConfiguration.js
  src/cartridges/int_adyen_SFRA/cartridge/client/default/js/adyen_checkout/helpers.js
  src/cartridges/int_adyen_SFRA/cartridge/client/default/js/adyen_checkout/makePartialPayment.js
  src/cartridges/int_adyen_SFRA/cartridge/client/default/js/adyen_checkout/renderGenericComponent.js
  src/cartridges/int_adyen_SFRA/cartridge/client/default/js/adyen_checkout/renderGiftcardComponent.js
  src/cartridges/int_adyen_overlay/cartridge/scripts/adyenSessions.js
Labels: fix
