Repository Adyen/adyen-salesforce-commerce-cloud, pull requests merged in 2023-02, with the labels that each got.

#835 PW-8078 Update API name for the field adyenPaymentMethod in SFCC
  metadata/site_import/meta/system-objecttype-extensions.xml
  src/cartridges/int_adyen_SFRA/cartridge/controllers/middlewares/adyen/paymentFromComponent.js
  src/cartridges/int_adyen_SFRA/cartridge/controllers/middlewares/checkout_services/placeOrder.js
  src/cartridges/int_adyen_SFRA/cartridge/scripts/hooks/payment/processor/middlewares/handle.js
Labels: new

#838 Revert "PW-7784: rerender express component"
  jsconfig.json
  package-lock.json
  src/cartridges/int_adyen_SFRA/cartridge/client/default/js/adyen_checkout/helpers.js
  src/cartridges/int_adyen_SFRA/cartridge/client/default/js/applePayExpress.js
  src/cartridges/int_adyen_SFRA/cartridge/scripts/JSUtils/debounce.js
  src/cartridges/int_adyen_SFRA/cartridge/scripts/JSUtils/index.js
  src/cartridges/int_adyen_SFRA/cartridge/store/index.js
  src/cartridges/int_adyen_SFRA/cartridge/templates/default/cart/checkoutButtons.isml
Labels: excluded

#840 Add oneclick to requestObject
  src/cartridges/int_adyen_overlay/cartridge/adyenConstants/constants.js
  src/cartridges/int_adyen_overlay/cartridge/scripts/adyenDeleteRecurringPayment.js
Labels: fix
