Repository Adyen/adyen-salesforce-commerce-cloud, pull requests merged in 2023-03, with the labels that each got.

#845 Rename releases to release yml
  .github/release.yml
Labels: excluded

#844 Express methods loader [SFRA]
  src/cartridges/int_adyen_SFRA/cartridge/client/default/js/amazonPayExpressPart1.js
  src/cartridges/int_adyen_SFRA/cartridge/client/default/js/applePayExpress.js
  src/cartridges/int_adyen_SFRA/cartridge/client/default/js/commons/index.js
  src/cartridges/int_adyen_SFRA/cartridge/client/default/js/expressPaymentMethodsVisibility.js
  src/cartridges/int_adyen_SFRA/cartridge/templates/default/cart/checkoutButtons.isml
  src/cartridges/int_adyen_overlay/cartridge/static/default/css/adyenCss.css
Labels: new

#847 Husky - Commitlint
  .husky/commit-msg
  .husky/pre-commit
  commitlint.config.js
  package-lock.json
  package.json
Labels: excluded

#846 Cancel button added for giftcards [SFRA]
  src/cartridges/int_adyen_SFRA/cartridge/client/default/js/adyen_checkout/checkoutConfiguration.js
  src/cartridges/int_adyen_SFRA/cartridge/client/default/js/adyen_checkout/renderGiftcardComponent.js
  src/cartridges/int_adyen_SFRA/cartridge/templates/default/checkout/billing/adyenComponentForm.isml
  src/cartridges/int_adyen_overlay/cartridge/static/default/css/adyenCss.css
  src/cartridges/int_adyen_overlay/cartridge/static/default/images/cancel.svg
Labels: fix

#848 Branch names convention
  .husky/pre-commit
  branching.sh
  package-lock.json
  package.json
  src/cartridges/int_adyen_SFRA/cartridge/client/default/js/adyenCheckout.js
  src/cartridges/int_adyen_SFRA/cartridge/client/default/js/adyen_checkout/checkoutConfiguration.js
  src/cartridges/int_adyen_SFRA/cartridge/client/default/js/adyen_checkout/renderGenericComponent.js
  src/cartridges/int_adyen_SFRA/cartridge/client/default/js/adyen_checkout/renderGiftcardComponent.js
  src/cartridges/int_adyen_SFRA/cartridge/client/default/js/amazonPayExpressPart1.js
  src/cartridges/int_adyen_SFRA/cartridge/controllers/middlewares/adyen/cancelPartialPaymentOrder.js
  src/cartridges/int_adyen_SFRA/cartridge/controllers/middlewares/adyen/partialPayment.js
  src/cartridges/int_adyen_SFRA/cartridge/controllers/middlewares/adyen/paymentFromComponent.js
  src/cartridges/int_adyen_SFRA/cartridge/controllers/middlewares/adyen/paymentsDetails.js
  src/cartridges/int_adyen_SFRA/cartridge/controllers/middlewares/adyen/redirect3ds1Response.js
  src/cartridges/int_adyen_SFRA/cartridge/controllers/middlewares/adyen/saveExpressShopperDetails.js
  src/cartridges/int_adyen_SFRA/cartridge/controllers/middlewares/adyen/shippingMethods.js
  src/cartridges/int_adyen_SFRA/cartridge/controllers/middlewares/adyen/showConfirmation.js
  src/cartridges/int_adyen_SFRA/cartridge/models/createPayment.js
  src/cartridges/int_adyen_SFRA/cartridge/scripts/hooks/payment/processor/middlewares/handle.js
Labels: excluded

#851 giftcard component on safari
  src/cartridges/int_adyen_SFRA/cartridge/client/default/js/adyen_checkout/__tests__/__snapshots__/renderGiftcardComponent.test.js.snap
  src/cartridges/int_adyen_SFRA/cartridge/client/default/js/adyen_checkout/renderGiftcardComponent.js
  src/cartridges/int_adyen_SFRA/cartridge/templates/default/checkout/billing/adyenComponentForm.isml
  src/cartridges/int_adyen_overlay/cartridge/static/default/css/adyenCss.css
Labels: fix

#862 Dependency updates
  .github/workflows/codeql-analysis.yml
  cartridges/int_adyen_SFRA/package.json
  package-lock.json
  package.json
  src/cartridges/int_adyen_SFRA/package.json
  src/cartridges/int_adyen_SFRA/test/integration/codecept.conf.js
  src/cartridges/int_adyen_SFRA/test/integration/config.js
  src/cartridges/int_adyen_SFRA/test/integration/customsteps.js
  src/cartridges/int_adyen_SFRA/test/integration/tests/Guest_test.js
  src/cartridges/int_adyen_SFRA/test/integration/tests/LoginUser_test.js
  src/cartridges/int_adyen_SFRA/test/integration/tsconfig.json
  src/cartridges/int_adyen_SFRA/test/mocks/dw/order/BasketMgr.js
  src/cartridges/int_adyen_SFRA/test/mocks/helpers/adyenHelpers.js
  src/cartridges/int_adyen_SFRA/test/unit/scripts/checkout/adyenCheckout.test.js
  src/cartridges/int_adyen_SFRA/test/unit/scripts/checkout/adyenHelpers.js
Labels: enhancement

#873 Oney E2E tests
  tests/playwright/fixtures/countriesEUR/FR.spec.mjs
  tests/playwright/pages/PaymentMethodsPage.mjs
  tests/playwright/paymentFlows/redirectShopper.mjs
Labels: fix

#880 Fix remaining amount label if order amount is covered by giftcard
  src/cartridges/int_adyen_SFRA/cartridge/client/default/js/adyen_checkout/checkoutConfiguration.js
  src/cartridges/int_adyen_SFRA/cartridge/client/default/js/adyen_checkout/renderGiftcardComponent.js
  src/cartridges/int_adyen_SFRA/cartridge/controllers/middlewares/adyen/checkBalance.js
Labels: fix

#885 Content changes in the configuration page
  src/cartridges/bm_adyen/cartridge/static/default/css/configurationSettings.css
  src/cartridges/bm_adyen/cartridge/templates/default/adyenSettings/settingCards/epmSettings.isml
  src/cartridges/bm_adyen/cartridge/templates/default/adyenSettings/settingCards/lpmSettings.isml
  src/cartridges/bm_adyen/cartridge/templates/default/adyenSettings/settingCards/requiredSettings.isml
Labels: fix

#894 Missing payment instrument case is breaking jobs
  src/cartridges/int_adyen_overlay/cartridge/adyenConstants/constants.js
  src/cartridges/int_adyen_overlay/cartridge/scripts/handleCustomObject.js
Labels: fix
