Repository Adyen/adyen-salesforce-commerce-cloud, pull requests merged in 2024-10, with the labels that each got.

#1180 Automated release upload to sandboxes
  .github/workflows/release-upload.yml
Labels: new, excluded

#1178 C2P customer email is set from basket
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/adyen_checkout/__tests__/checkoutConfiguration.test.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/adyen_checkout/checkoutConfiguration.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/adyen_checkout/renderGiftcardComponent.js
  src/cartridges/app_adyen_SFRA/cartridge/templates/default/checkout/billing/adyenComponentForm.isml
  src/cartridges/int_adyen_SFRA/cartridge/adyen/utils/adyenHelper.js
Labels: fix

#1181 Updating web components, new upi config
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/adyen_checkout/checkoutConfiguration.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/constants.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/config/constants.js
  tests/playwright/fixtures/INR.spec.mjs
  tests/playwright/fixtures/USD.spec.mjs
  tests/playwright/fixtures/countriesEUR/DE.spec.mjs
  tests/playwright/fixtures/countriesEUR/FR.spec.mjs
  tests/playwright/fixtures/countriesEUR/NL.spec.mjs
  tests/playwright/pages/CheckoutPageSFRA5.mjs
  tests/playwright/pages/CheckoutPageSFRA6.mjs
  tests/playwright/pages/PaymentMethodsPage.mjs
  tests/playwright/paymentFlows/redirectShopper.mjs
Labels: new

#1182 E2E Maintenance
  tests/playwright/fixtures/USD.spec.mjs
  tests/playwright/fixtures/countriesEUR/DE.spec.mjs
  tests/playwright/fixtures/countriesEUR/FR.spec.mjs
  tests/playwright/package.json
  tests/playwright/pages/AccountPageSFRA.mjs
  tests/playwright/pages/CheckoutPageSFRA5.mjs
  tests/playwright/pages/CheckoutPageSFRA6.mjs
  tests/playwright/pages/PaymentMethodsPage.mjs
  tests/playwright/paymentFlows/pending.mjs
  tests/playwright/paymentFlows/redirectShopper.mjs
  tests/playwright/sfcc.config.js
Labels: excluded

#1188 Adding the C2P shopperEmail upon initial rendering
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/adyenCheckout.js
Labels: fix

#1193 applepay unit tests
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/__tests__/applePayExpress.test.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/applePayExpressCommon.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/product/detail.js
Labels: excluded

#1203 PayPal express taxation test
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/adyen_checkout/checkoutConfiguration.js
  tests/playwright/fixtures/USD.spec.mjs
  tests/playwright/pages/CheckoutPageSFRA6.mjs
  tests/playwright/pages/PaymentMethodsPage.mjs
  tests/playwright/paymentFlows/redirectShopper.mjs
Labels: excluded

#1199 Click to pay e2e
  tests/playwright/data/paymentData.mjs
  tests/playwright/fixtures/countriesEUR/NL.spec.mjs
  tests/playwright/pages/CheckoutPageSFRA5.mjs
  tests/playwright/pages/CheckoutPageSFRA6.mjs
Labels: excluded
