Repository Adyen/adyen-salesforce-commerce-cloud, pull requests merged in 2024-04, with the labels that each got.

#1063 Upgrade Checkout components and add telemetry info
  src/cartridges/int_adyen_SFRA/cartridge/client/default/js/amazonPayExpressPart1.js
  src/cartridges/int_adyen_SFRA/cartridge/client/default/js/amazonPayExpressPart2.js
  src/cartridges/int_adyen_SFRA/cartridge/client/default/js/applePayExpress.js
  src/cartridges/int_adyen_SFRA/cartridge/controllers/middlewares/adyen/__tests__/getCheckoutPaymentMethods.test.js
  src/cartridges/int_adyen_SFRA/cartridge/controllers/middlewares/adyen/getCheckoutPaymentMethods.js
  src/cartridges/int_adyen_overlay/cartridge/adyenConstants/constants.js
Labels: new

#1066 Passing amount to giftcard component on creation
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/adyen_checkout/renderGiftcardComponent.js
Labels: fix

#1065 GitHub pipeline adjustement
  .github/workflows/cartridges-commit.yml
Labels: excluded

#1068 Merging changes of develop into SFI-544
  .eslintrc.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/adyen_checkout/renderGenericComponent.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/adyen_checkout/renderGiftcardComponent.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/amazonPayExpressPart1.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/amazonPayExpressPart2.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/applePayExpress.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/config/constants.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/payments/__tests__/getCheckoutPaymentMethods.test.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/payments/getCheckoutPaymentMethods.js
  tests/playwright/pages/PaymentMethodsPage.mjs
Labels: excluded

#1075 Enabling github actions for SFRA 7
  .github/workflows/E2E_SFRA.yml
  tests/playwright/data/environments.mjs
  tests/playwright/fixtures/BRL.spec.mjs
  tests/playwright/fixtures/DKK.spec.mjs
  tests/playwright/fixtures/INR.spec.mjs
  tests/playwright/fixtures/JPY.spec.mjs
  tests/playwright/fixtures/NOK.spec.mjs
  tests/playwright/fixtures/SEK.spec.mjs
  tests/playwright/fixtures/USD.spec.mjs
  tests/playwright/fixtures/countriesEUR/AT.spec.mjs
  tests/playwright/fixtures/countriesEUR/BE.spec.mjs
  tests/playwright/fixtures/countriesEUR/DE.spec.mjs
  tests/playwright/fixtures/countriesEUR/FR.spec.mjs
  tests/playwright/fixtures/countriesEUR/NL.spec.mjs
  tests/playwright/fixtures/countriesEUR/PT.spec.mjs
  tests/playwright/package-lock.json
Labels: excluded
