Repository Adyen/adyen-salesforce-commerce-cloud, pull requests merged in 2024-11, with the labels that each got.

#1204 Lint files
  .eslintignore
  .eslintrc.js
  ismllinter.config.js
  package.json
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/payments/adyenGetOpenInvoiceData.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/utils/adyenConfigs.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/utils/lineItemHelper.js
Labels: excluded

#1205 Added jcb config for installments
  src/cartridges/bm_adyen/cartridge/static/default/js/adyenSettings.js
Labels: new

#1206 Apple Pay on PDP
  .eslintrc.js
  jest/sfccCartridgeMocks.js
  metadata/site_import/meta/system-objecttype-extensions.xml
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/__tests__/applePayExpress.test.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/adyen_checkout/__tests__/applePayExpress.test.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/adyen_checkout/__tests__/makePartialPayment.test.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/adyen_checkout/__tests__/renderGenericComponent.test.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/adyen_checkout/renderGenericComponent.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/amazonPayExpressPart1.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/amazonPayExpressPart2.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/applePayExpress.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/applePayExpressCommon.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/commons/index.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/paypalExpress.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/product/expressPayments.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/productDetail.js
  src/cartridges/app_adyen_SFRA/cartridge/templates/default/product/components/addToCartButtonExtension.isml
  src/cartridges/bm_adyen/cartridge/static/default/css/configurationSettings.css
  src/cartridges/bm_adyen/cartridge/static/default/js/adyenSettings.js
  src/cartridges/bm_adyen/cartridge/templates/default/adyenSettings/navigationCard.isml
  src/cartridges/bm_adyen/cartridge/templates/default/adyenSettings/quickLinksCard.isml
  src/cartridges/bm_adyen/cartridge/templates/default/adyenSettings/settingCards/epmSettings.isml
  src/cartridges/bm_adyen/cartridge/templates/default/adyenSettings/settings.isml
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/expressPayments/createTemporaryBasket.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/expressPayments/selectShippingMethods.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/expressPayments/shippingMethods.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/index.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/payments/__tests__/getCheckoutPaymentMethods.test.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/payments/adyenGetPaymentMethods.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/payments/getCheckoutPaymentMethods.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/payments/paymentFromComponent.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/payments/updateSavedCards.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/utils/adyenConfigs.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/utils/adyenHelper.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/utils/lineItemHelper.js
  src/cartridges/int_adyen_SFRA/cartridge/controllers/Adyen.js
Labels: new

#1209 Update renovate bot config
  renovate.json
Labels: excluded

#1208 Giftcards unit tests
  jest/__mocks__/dw/value/Money.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/partialPayments/__tests__/cancelPartialPaymentOrder.test.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/partialPayments/__tests__/checkBalance.test.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/partialPayments/__tests__/fetchGiftCards.test.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/utils/__tests__/giftCardsHelper.test.js
Labels: excluded

#1207 Adding a retry logic to the job in case of failure
  metadata/site_import/jobs.xml
  metadata/site_import/meta/custom-objecttype-definitions.xml
  src/cartridges/int_adyen_SFRA/cartridge/adyen/analytics/analyticsEvents.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/analytics/job/analyticsJob.js
Labels: new

#1211 One payment methods call for all express payments
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/__tests__/applePayExpress.test.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/__tests__/paypalExpress.test.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/adyen_checkout/__tests__/applePayExpress.test.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/amazonPayExpressPart1.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/applePayExpress.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/applePayExpressCommon.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/expressPaymentMethodsVisibility.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/expressPayments.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/paypalExpress.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/product/expressPayments.js
  src/cartridges/app_adyen_SFRA/cartridge/static/default/css/adyenCss.css
  src/cartridges/app_adyen_SFRA/cartridge/templates/default/cart/checkoutButtons.isml
Labels: fix

#1212 Adding one more validation to the get endpoint
  src/cartridges/bm_adyen/cartridge/controllers/AdyenSettings.js
Labels: refactor

#1214 Replace fetch with ajax
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/__tests__/applePayExpress.test.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/__tests__/paypalExpress.test.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/adyen_checkout/__tests__/renderGenericComponent.test.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/adyen_checkout/renderGenericComponent.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/amazonPayExpressPart2.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/applePayExpress.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/commons/index.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/expressPayments.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/paypalExpress.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/product/expressPayments.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/expressPayments/__tests__/selectShippingMethods.test.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/expressPayments/__tests__/shippingMethods.test.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/expressPayments/createTemporaryBasket.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/expressPayments/selectShippingMethods.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/expressPayments/shippingMethods.js
  src/cartridges/int_adyen_SFRA/cartridge/controllers/Adyen.js
Labels: refactor

#1216 Reject giftcard
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/adyen_checkout/checkoutConfiguration.js
Labels: fix

#1218 Redirect to confirmation page for POS
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/adyen_checkout/renderGenericComponent.js
  src/cartridges/int_adyen_SFRA/cartridge/controllers/middlewares/checkout_services/placeOrder.js
Labels: new
