Repository Adyen/adyen-salesforce-commerce-cloud, pull requests merged in 2024-07, with the labels that each got.

#1101 Updating e2e test for amazon pay express
  tests/playwright/fixtures/countriesEUR/FR.spec.mjs
  tests/playwright/pages/PaymentMethodsPage.mjs
Labels: fix, excluded

#1099 Upgrade dev dependencies
  .github/workflows/E2E_SFRA.yml
  .github/workflows/SFCC.yml
  .github/workflows/cartridges-commit.yml
  .github/workflows/codeql-analysis.yml
  package-lock.json
  package.json
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/adyen_checkout/checkoutConfiguration.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/adyen_checkout/renderGiftcardComponent.js
Labels: excluded

#1104 Include diagrams in documentation
  documentation/Adyen SFCC Docs.md
  documentation/README.md
  documentation/diagrams/amazon-pay-express.png
  documentation/diagrams/apple-pay-express.png
  documentation/diagrams/get-payment-methods.png
  documentation/diagrams/multiple-giftcards-flow.png
  documentation/diagrams/payment-from-component.png
  documentation/diagrams/payment-with-action.png
  documentation/diagrams/payment-without-action.png
  documentation/diagrams/single-giftcard-flow.png
  documentation/diagrams/webhooks-flow.png
Labels: excluded

#1107 Changed the manufacturer field name to align with API requirements
  src/cartridges/int_adyen_SFRA/cartridge/adyen/utils/riskDataHelper.js
Labels: fix

#1115 Merging develop into SFI-42 and adding required mocks
  documentation/Adyen SFCC Docs.md
  documentation/README.md
  documentation/diagrams/amazon-pay-express.png
  documentation/diagrams/apple-pay-express.png
  documentation/diagrams/get-payment-methods.png
  documentation/diagrams/multiple-giftcards-flow.png
  documentation/diagrams/payment-from-component.png
  documentation/diagrams/payment-with-action.png
  documentation/diagrams/payment-without-action.png
  documentation/diagrams/single-giftcard-flow.png
  documentation/diagrams/webhooks-flow.png
  jest/__mocks__/dw/crypto/Encoding.js
  jest/__mocks__/dw/crypto/MessageDigest.js
  jest/__mocks__/dw/order/ShippingLocation.js
  jest/__mocks__/dw/order/TaxMgr.js
  jest/__mocks__/dw/svc/LocalServiceRegistry.js
  jest/__mocks__/dw/util/Bytes.js
  jest/__mocks__/dw/util/Currency.js
  jest/sfccCartridgeMocks.js
  jest/sfccPathSetup.js
  package-lock.json
  package.json
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/adyen_checkout/__tests__/amazonPayExpressPart2.test.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/adyen_checkout/__tests__/applePayExpress.test.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/adyen_checkout/checkoutConfiguration.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/adyen_checkout/renderGiftcardComponent.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/amazonPayExpressPart2.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/applePayExpress.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/constants.js
  src/cartridges/bm_adyen/cartridge/templates/default/order/PaymentInstrumentInfo_Adyen.isml
  src/cartridges/bm_adyen/cartridge/templates/default/order/PaymentInstrumentInfo_Adyen_Component.isml
  src/cartridges/int_adyen_SFRA/cartridge/adyen/config/constants.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/expressPayments/__tests__/shippingMethods.test.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/payments/adyenCheckout.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/utils/__tests__/adyenHelper.test.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/utils/adyenHelper.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/utils/riskDataHelper.js
  tests/playwright/fixtures/countriesEUR/FR.spec.mjs
  tests/playwright/pages/PaymentMethodsPage.mjs
Labels: excluded

#1117 Added e2e tests for paypal express
  src/cartridges/app_adyen_SFRA/cartridge/templates/default/cart/checkoutReview.isml
  tests/playwright/fixtures/USD.spec.mjs
  tests/playwright/pages/PaymentMethodsPage.mjs
  tests/playwright/paymentFlows/redirectShopper.mjs
Labels: new

#1120 Adding metadata upload workflow
  .github/workflows/metadata-upload.yml
Labels: excluded

#1123 Remove redunadant check in for donations
  src/cartridges/int_adyen_SFRA/cartridge/adyen/utils/adyenHelper.js
Labels: refactor

#1124 BCMC config is set wrong
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/adyen_checkout/checkoutConfiguration.js
Labels: fix

#1116 paypal diagram
  documentation/README.md
  documentation/diagrams/paypal-express.png
Labels: excluded

#1125 Bumping the version to 24.3.0
  package-lock.json
  package.json
  src/cartridges/int_adyen_SFRA/cartridge/adyen/config/constants.js
Labels: excluded

#1127 chore: adding --no-verify in the pipeline for commiting
  .github/workflows/cartridges-commit.yml
Labels: excluded

#1129 linting and formatting of the e2e test files
  tests/playwright/fixtures/BRL.spec.mjs
  tests/playwright/fixtures/DKK.spec.mjs
  tests/playwright/fixtures/INR.spec.mjs
  tests/playwright/fixtures/JPY.spec.mjs
  tests/playwright/fixtures/NOK.spec.mjs
  tests/playwright/fixtures/SEK.spec.mjs
  tests/playwright/fixtures/USD.spec.mjs
  tests/playwright/fixtures/countriesEUR/AT.spec.mjs
  tests/playwright/fixtures/countriesEUR/BE.spec.mjs
  tests/playwright/fixtures/countriesEUR/DE.spec.mjs
  tests/playwright/fixtures/countriesEUR/FR.spec.mjs
  tests/playwright/fixtures/countriesEUR/NL.spec.mjs
  tests/playwright/fixtures/countriesEUR/PT.spec.mjs
Labels: excluded

#1130 Initialize payment methods objects properly
  src/cartridges/app_adyen_SFRA/cartridge/store/index.js
  tests/playwright/pages/PaymentMethodsPage.mjs
Labels: fix
