Repository Adyen/adyen-salesforce-commerce-cloud, pull requests merged in 2024-08, with the labels that each got.

#1132 Check whether node is initiated before applying validations
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/adyen_checkout/helpers.js
Labels: fix

#1133 Compliance with the new Visa Secure Authentication requirements
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/adyen_checkout/checkoutConfiguration.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/adyen_checkout/renderGiftcardComponent.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/payments/__tests__/adyenCheckout.test.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/payments/adyenCheckout.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/payments/adyenZeroAuth.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/utils/adyenHelper.js
Labels: new

#1135 Include holder name in state data
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/adyen_checkout/__tests__/checkoutConfiguration.test.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/adyen_checkout/checkoutConfiguration.js
  tests/playwright/fixtures/countriesEUR/FR.spec.mjs
Labels: fix

#1134 Tax calculation for paypal express
  jest/__mocks__/dw/order/BasketMgr.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/expressPayments/paypal/makeExpressPaymentsCall.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/expressPayments/shippingMethods.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/utils/__tests__/paypalHelper.test.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/utils/adyenHelper.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/utils/paypalHelper.js
Labels: fix

#1139 Bugfix/paypal express currency
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/__tests__/__snapshots__/paypalExpress.test.js.snap
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/__tests__/paypalExpress.test.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/adyen_checkout/checkoutConfiguration.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/adyen_checkout/renderGiftcardComponent.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/paypalExpress.js
Labels: fix

#1146 Removing the end of line logic from domain association
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/adyen_checkout/checkoutConfiguration.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/adyen_checkout/renderGiftcardComponent.js
  src/cartridges/int_adyen_SFRA/cartridge/controllers/RedirectURL.js
Labels: refactor

#1149 Pass correct payment instrument to the payments request
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/hooks/payment/processor/middlewares/authorize.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/payments/__tests__/adyenCheckout.test.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/payments/adyenCheckout.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/payments/paymentFromComponent.js
Labels: fix

#1150 Added stack trace to error logs and fatal logs
  src/cartridges/bm_adyen/cartridge/controllers/AdyenSettings.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/donations/adyenGiving.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/expressPayments/saveExpressShopperDetails.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/hooks/payment/processor/middlewares/__tests__/__snapshots__/posAuthorize.test.js.snap
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/hooks/payment/processor/middlewares/__tests__/posAuthorize.test.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/hooks/payment/processor/middlewares/authorize.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/hooks/payment/processor/middlewares/posAuthorize.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/hooks/payment/processor/middlewares/processForm.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/partialPayments/cancelPartialPaymentOrder.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/partialPayments/checkBalance.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/partialPayments/fetchGiftCards.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/partialPayments/partialPayment.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/partialPayments/partialPaymentsOrder.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/payments/adyenCheckout.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/payments/adyenDeleteRecurringPayment.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/payments/adyenGetPaymentMethods.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/payments/adyenTerminalApi.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/payments/adyenZeroAuth.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/payments/getCheckoutPaymentMethods.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/payments/paymentsDetails.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/payments/redirect3ds1Response.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/payments/updateSavedCards.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/showConfirmation/showConfirmation.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/showConfirmation/showConfirmationPaymentFromComponent.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/utils/adyenHelper.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/webhooks/deleteCustomObjects.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/webhooks/handleNotify.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/webhooks/libs/libAuthenticationUtils.js
  src/cartridges/int_adyen_SFRA/cartridge/controllers/middlewares/checkout/begin.js
Labels: new

#1151 Adyen endpoints optimization
  package-lock.json
  package.json
  src/cartridges/int_adyen_SFRA/cartridge/client/default/js/commons/index.js
  src/cartridges/int_adyen_SFRA/cartridge/controllers/Adyen.js
  src/cartridges/int_adyen_SFRA/cartridge/templates/default/account/payment/paymentForm.isml
  src/cartridges/int_adyen_SFRA/cartridge/templates/default/checkout/billing/adyenComponentForm.isml
  src/cartridges/int_adyen_controllers/cartridge/templates/default/checkout/billing/adyenComponent.isml
  src/cartridges/int_adyen_overlay/cartridge/adyenConstants/constants.js
Labels: refactor
