Repository Adyen/adyen-salesforce-commerce-cloud, pull requests merged in 2024-09, with the labels that each got.

#1157 Adding line items for riverty
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/payments/adyenCheckout.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/utils/adyenHelper.js
Labels: new

#1159 Updating dependencies
  package-lock.json
  package.json
  tests/playwright/package-lock.json
  tests/playwright/package.json
Labels: excluded

#1169 E2E tests for riverty
  src/cartridges/app_adyen_SFRA/cartridge/config/countries.json
  tests/playwright/data/enums.mjs
  tests/playwright/data/shopperData.mjs
  tests/playwright/fixtures/countriesEUR/DE.spec.mjs
  tests/playwright/pages/CheckoutPageSFRA5.mjs
  tests/playwright/pages/CheckoutPageSFRA6.mjs
  tests/playwright/pages/PaymentMethodsPage.mjs
  tests/playwright/paymentFlows/redirectShopper.mjs
Labels: excluded

#1172 Bugfix/paypal tax gross
  jest/__mocks__/dw/order/TaxMgr.js
  jest/__mocks__/dw/value/Money.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/adyen_checkout/checkoutConfiguration.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/adyen_checkout/renderGiftcardComponent.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/expressPayments/paypal/makeExpressPaymentsCall.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/utils/adyenHelper.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/utils/paypalHelper.js
Labels: fix

#1170 Improving the endpoint validations
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/__tests__/paypalExpress.test.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/adyenAccount.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/adyenGiving.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/adyen_checkout/checkoutConfiguration.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/adyen_checkout/helpers.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/adyen_checkout/makePartialPayment.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/adyen_checkout/renderGiftcardComponent.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/amazonPayCheckout.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/amazonPayExpressPart2.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/applePayExpress.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/checkoutReviewButtons.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/paypalExpress.js
  src/cartridges/app_adyen_SFRA/cartridge/templates/default/account/payment/paymentForm.isml
  src/cartridges/app_adyen_SFRA/cartridge/templates/default/adyen/checkoutReviewButtons.isml
  src/cartridges/app_adyen_SFRA/cartridge/templates/default/cart/checkoutButtons.isml
  src/cartridges/app_adyen_SFRA/cartridge/templates/default/cart/checkoutReview.isml
  src/cartridges/app_adyen_SFRA/cartridge/templates/default/checkout/billing/adyenComponentForm.isml
  src/cartridges/app_adyen_SFRA/cartridge/templates/default/checkout/billing/adyenGivingComponent.isml
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/expressPayments/paypal/__tests__/makeExpressPaymentDetailsCall.test.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/expressPayments/paypal/__tests__/makeExpressPaymentsCall.test.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/expressPayments/paypal/makeExpressPaymentDetailsCall.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/expressPayments/paypal/makeExpressPaymentsCall.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/partialPayments/cancelPartialPaymentOrder.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/partialPayments/checkBalance.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/partialPayments/partialPayment.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/payments/__tests__/paymentsDetails.test.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/payments/paymentsDetails.js
  src/cartridges/int_adyen_SFRA/cartridge/controllers/Adyen.js
  src/cartridges/int_adyen_SFRA/cartridge/controllers/Cart.js
Labels: refactor

#1176 Change the url link depending on the environment in Business Manager
  src/cartridges/bm_adyen/cartridge/templates/default/order/PaymentInstrumentInfo_Adyen.isml
  src/cartridges/bm_adyen/cartridge/templates/default/order/PaymentInstrumentInfo_Adyen_Component.isml
Labels: fix

#1177 Provide street number for klarna
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/payments/adyenCheckout.js
Labels: refactor
