Repository Adyen/adyen-salesforce-commerce-cloud, pull requests merged in 2024-06, with the labels that each got.

#1086 PayPal Express update order
  .github/workflows/SFCC.yml
  cartridges/int_adyen_SFRA/cartridge/adyen/scripts/expressPayments/shippingMethods.js
  jest/__mocks__/dw/util/UUIDUtils.js
  jest/sfccCartridgeMocks.js
  jest/sfccPathSetup.js
  metadata/site_import/services.xml
  sonar-project.properties
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/amazonPayExpressPart1.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/applePayExpress.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/commons/index.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/constants.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/paypalExpress.js
  src/cartridges/app_adyen_SFRA/cartridge/templates/default/cart/checkoutButtons.isml
  src/cartridges/int_adyen_SFRA/cartridge/adyen/config/constants.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/logs/adyenCustomLogs.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/expressPayments/__tests__/selectShippingMethods.test.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/expressPayments/__tests__/shippingMethods.test.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/expressPayments/paypal/makeExpressPaymentsCall.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/expressPayments/saveExpressShopperDetails.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/expressPayments/selectShippingMethods.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/expressPayments/shippingMethods.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/payments/__tests__/adyenCheckout.test.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/payments/__tests__/getCheckoutPaymentMethods.test.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/payments/__tests__/paymentsDetails.test.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/payments/__tests__/paypalHelper.test.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/payments/adyenCheckout.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/payments/adyenZeroAuth.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/payments/getCheckoutPaymentMethods.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/payments/paymentsDetails.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/payments/paypalHelper.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/showConfirmation/handlePaymentFromComponent.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/utils/__tests__/paypalHelper.test.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/utils/adyenHelper.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/utils/paypalHelper.js
  src/cartridges/int_adyen_SFRA/cartridge/controllers/Adyen.js
Labels: new

#1091 add spinner for paypal express flow
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/paypalExpress.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/expressPayments/paypal/makeExpressPaymentDetailsCall.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/expressPayments/paypal/saveShopperData.js
Labels: new

#1092 Bumping the version to 24.2.1
  package-lock.json
  package.json
  src/cartridges/int_adyen_SFRA/cartridge/adyen/config/constants.js
  tests/playwright/pages/PaymentMethodsPage.mjs
Labels: excluded

#1093 Added a check to set address properties in case they are available
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/expressPayments/shippingMethods.js
Labels: fix

#1090 Updating web components, enabling new flow for iDeal
  src/cartridges/int_adyen_SFRA/cartridge/adyen/config/constants.js
  tests/playwright/fixtures/countriesEUR/NL.spec.mjs
  tests/playwright/pages/CheckoutPageSFRA5.mjs
  tests/playwright/pages/CheckoutPageSFRA6.mjs
  tests/playwright/pages/PaymentMethodsPage.mjs
  tests/playwright/paymentFlows/redirectShopper.mjs
Labels: new

#1096 Added the review page template and controller to render it
  jest/sfccPathSetup.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/paypalExpress.js
  src/cartridges/app_adyen_SFRA/cartridge/templates/default/cart/checkoutButtons.isml
  src/cartridges/app_adyen_SFRA/cartridge/templates/default/cart/checkoutReview.isml
  src/cartridges/int_adyen_SFRA/cartridge/adyen/config/constants.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/expressPayments/paypal/handleCheckoutReview.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/index.js
  src/cartridges/int_adyen_SFRA/cartridge/controllers/Adyen.js
  tests/playwright/fixtures/countriesEUR/NL.spec.mjs
  tests/playwright/pages/CheckoutPageSFRA5.mjs
  tests/playwright/pages/CheckoutPageSFRA6.mjs
  tests/playwright/pages/PaymentMethodsPage.mjs
  tests/playwright/paymentFlows/redirectShopper.mjs
Labels: new
