Repository Adyen/adyen-salesforce-commerce-cloud, pull requests merged in 2025-01, with the labels that each got.

#1236 Added support to card brands configured in merchant account in account page
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/adyenAccount.js
  src/cartridges/app_adyen_SFRA/cartridge/templates/default/account/payment/paymentForm.isml
  tests/playwright/pages/CheckoutPageSFRA5.mjs
Labels: new

#1240 Enabling Atome
  src/cartridges/int_adyen_SFRA/cartridge/adyen/config/constants.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/utils/adyenHelper.js
Labels: fix

#1244 Upgrade github artifacts version
  .github/workflows/E2E_SFRA.yml
Labels: excluded
