Repository Adyen/adyen-salesforce-commerce-cloud, pull requests merged in 2025-09, with the labels that each got.

#1395 [SFI-1365] Upgrade adyen web version
  src/cartridges/int_adyen_SFRA/cartridge/adyen/config/constants.js
  tests/playwright/pages/PaymentMethodsPage.mjs
Labels: new

#1404 [SFI-1368] Fix Google Pay (3ds2) payments
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/adyen/checkout/helpers.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/adyen/checkout/paymentMethodsConfiguration/googlePay/googlePayConfig.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/adyen/express/__tests__/googlePayExpress.test.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/adyen/express/paymentMethods/googlepay/googlepay.js
Labels: fix

#1408 [SFI-1392] Cashapp renders correctly on new page load
  package-lock.json
  package.json
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/adyen/checkout/renderPaymentMethod.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/config/constants.js
  tests/playwright/fixtures/USD.spec.mjs
Labels: fix

#1402 [SFI-1363] Post auth hook inside the cartrdige
  jest/sfccPathSetup.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/hooks.json
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/hooks/payment/postAuthorizationHandling.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/hooks/payment/processor/middlewares/authorize.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/showConfirmation/handlePaymentFromComponent.js
  src/cartridges/int_adyen_SFRA/cartridge/controllers/middlewares/checkout_services/placeOrder.js
Labels: refactor, do-not-merge

#1412 [SFI-1387] PDP cancel payment
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/adyen/checkout/helpers.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/adyen/express/paymentMethods/applepay/applepay.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/adyen/express/paymentMethods/googlepay/googlepay.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/showConfirmation/handlePaymentFromComponent.js
Labels: fix
