Repository Adyen/adyen-salesforce-commerce-cloud, pull requests merged in 2025-02, with the labels that each got.

#1243 Google Pay Express
  metadata/site_import/meta/system-objecttype-extensions.xml
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/__tests__/googlePayExpress.test.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/adyen_checkout/__tests__/renderGenericComponent.test.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/commons/index.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/constants.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/expressPayments.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/googlePayExpress.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/product/expressPayments.js
  src/cartridges/app_adyen_SFRA/cartridge/static/default/css/adyenCss.css
  src/cartridges/app_adyen_SFRA/cartridge/templates/default/cart/checkoutButtons.isml
  src/cartridges/app_adyen_SFRA/cartridge/templates/default/product/components/addToCartButtonExtension.isml
  src/cartridges/bm_adyen/cartridge/static/default/icons/googlepay.svg
  src/cartridges/bm_adyen/cartridge/static/default/js/adyenSettings.js
  src/cartridges/bm_adyen/cartridge/templates/default/adyenSettings/settingCards/epmSettings.isml
  src/cartridges/int_adyen_SFRA/cartridge/adyen/config/constants.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/payments/paymentFromComponent.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/showConfirmation/handlePaymentFromComponent.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/utils/adyenConfigs.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/utils/adyenHelper.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/utils/validatePaymentData.js
  src/cartridges/int_adyen_SFRA/cartridge/controllers/Adyen.js
  tests/playwright/data/paymentData.mjs
  tests/playwright/fixtures/USD.spec.mjs
  tests/playwright/fixtures/countriesEUR/DE.spec.mjs
  tests/playwright/fixtures/countriesEUR/NL.spec.mjs
  tests/playwright/pages/PaymentMethodsPage.mjs
  tests/playwright/paymentFlows/redirectShopper.mjs
Labels: new

#1254 http api client
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/__tests__/applePayExpress.test.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/__tests__/googlePayExpress.test.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/__tests__/paypalExpress.test.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/adyenAccount.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/adyenCheckout.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/adyenGiving.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/adyen_checkout/__tests__/adyenAccount.test.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/adyen_checkout/__tests__/amazonPayExpressPart2.test.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/adyen_checkout/__tests__/applePayExpress.test.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/adyen_checkout/__tests__/checkoutConfiguration.test.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/adyen_checkout/__tests__/helpers.test.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/adyen_checkout/__tests__/makePartialPayment.test.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/adyen_checkout/__tests__/renderGenericComponent.test.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/adyen_checkout/checkoutConfiguration.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/adyen_checkout/helpers.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/adyen_checkout/makePartialPayment.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/adyen_checkout/renderGenericComponent.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/adyen_checkout/renderGiftcardComponent.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/amazonPayCheckout.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/amazonPayExpressPart2.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/applePayExpress.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/checkoutReviewButtons.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/commons/httpClient.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/commons/index.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/googlePayExpress.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/paypalExpress.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/product/expressPayments.js
Labels: excluded

#1256 Adding extra validation logic for paypal express flow
  jest/__mocks__/dw/order/BasketMgr.js
  jest/sfccCartridgeMocks.js
  metadata/site_import/meta/system-objecttype-extensions.xml
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/expressPayments/paypal/__tests__/makeExpressPaymentDetailsCall.test.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/expressPayments/paypal/__tests__/makeExpressPaymentsCall.test.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/expressPayments/paypal/makeExpressPaymentDetailsCall.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/expressPayments/paypal/makeExpressPaymentsCall.js
Labels: refactor

#1258 Added extra validations for paypal express
  .github/workflows/E2E_SFRA.yml
  jest/__mocks__/dw/order/BasketMgr.js
  jest/sfccCartridgeMocks.js
  metadata/site_import/meta/system-objecttype-extensions.xml
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/expressPayments/paypal/__tests__/makeExpressPaymentDetailsCall.test.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/expressPayments/paypal/__tests__/makeExpressPaymentsCall.test.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/expressPayments/paypal/makeExpressPaymentDetailsCall.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/expressPayments/paypal/makeExpressPaymentsCall.js
Labels: refactor

#1257 PDP basket validation
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/__tests__/paypalExpress.test.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/applePayExpress.js
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/paypalExpress.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/partialPayments/partialPayment.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/payments/__tests__/adyenCheckout.test.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/payments/adyenCheckout.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/payments/adyenZeroAuth.js
Labels: refactor

#1264 Intermediate result codes
  src/cartridges/app_adyen_SFRA/cartridge/templates/default/checkout/confirmation/confirmation.isml
  src/cartridges/int_adyen_SFRA/cartridge/adyen/utils/adyenHelper.js
Labels: refactor

#1265 New front-end region for APSE
  src/cartridges/bm_adyen/cartridge/templates/default/adyenSettings/settingCards/requiredSettings.isml
  src/cartridges/int_adyen_SFRA/cartridge/adyen/config/constants.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/utils/adyenHelper.js
Labels: new

#1272 Handle on error for klarna
  src/cartridges/app_adyen_SFRA/cartridge/client/default/js/adyen_checkout/checkoutConfiguration.js
Labels: fix

#1270 Adyen Uplift
  jest/globals.js
  jest/sfccCartridgeMocks.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/expressPayments/paypal/makeExpressPaymentsCall.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/partialPayments/partialPayment.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/payments/adyenCheckout.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/payments/adyenGetPaymentMethods.js
  src/cartridges/int_adyen_SFRA/cartridge/adyen/scripts/payments/getCheckoutPaymentMethods.js
Labels: new
